import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#13172e' },
  header: {
    backgroundColor: '#1a1f3c',
    paddingTop: 52,
    paddingBottom: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#242a4e',
    gap: 12,
  },
  backBtn: { padding: 4 },
  headerTitleCol: { flex: 1 },
  headerCourseName: {
    color: '#d8ddf5',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  headerSubtitle: {
    color: '#9099b2',
    fontSize: 12,
    marginTop: 2,
  },

  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12 },
  loadingText: { color: '#9099b2', fontSize: 14 },
  errorText: {
    color: '#e05c7a',
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  retryBtn: {
    marginTop: 8,
    backgroundColor: '#4f6ef7',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
  },
  retryBtnText: { color: '#fff', fontWeight: '700', fontSize: 14 },

  progressBarWrap: {
    backgroundColor: '#1a1f3c',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#242a4e',
  },
  progressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  progressLabel: { color: '#9099b2', fontSize: 12 },
  progressPercent: { color: '#4f6ef7', fontSize: 12, fontWeight: '700' },
  progressTrack: {
    height: 4,
    backgroundColor: '#242a4e',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: 4,
    backgroundColor: '#4f6ef7',
    borderRadius: 2,
  },

  scrollContent: { padding: 20, paddingBottom: 40 },

  slideImageWrapper: {
    width: '100%',
    aspectRatio: 4 / 3,
    backgroundColor: '#0d1124',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#242a4e',
  },
  slideImage: {
    width: '100%',
    height: '100%',
  },

  slideNumberBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#242a4e',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  slideNumberText: { color: '#9099b2', fontSize: 12, fontWeight: '600' },

  transcriptCard: {
    backgroundColor: '#1a1f3c',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#242a4e',
    padding: 10,
  },
  transcriptLabel: {
    color: '#4f6ef7',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  transcriptText: {
    color: '#d8ddf5',
    fontSize: 16,
    lineHeight: 26,
    includeFontPadding: false,
    textAlignVertical: 'top',
  },

  controls: {
    backgroundColor: '#1a1f3c',
    borderTopWidth: 1,
    borderTopColor: '#242a4e',
    paddingHorizontal: 24,
    paddingVertical: 18,
    paddingBottom: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  controlBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#242a4e',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playPauseBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#4f6ef7',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4f6ef7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },

  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: '#13172e',
  },
  timeText: { color: '#5a6080', fontSize: 11 },

  completeCard: {
    backgroundColor: '#1b3d2e',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2ecc71',
    padding: 28,
    alignItems: 'center',
    gap: 10,
    marginTop: 20,
  },
  completeTitle: {
    color: '#2ecc71',
    fontSize: 22,
    fontWeight: '800',
  },
  completeSubtitle: {
    color: '#9099b2',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
  },

  takeTestBtn: {
    backgroundColor: '#4f6ef7',
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 12,
    shadowColor: '#4f6ef7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  takeTestBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },

  questionCard: {
    backgroundColor: '#1a1f3c',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#242a4e',
    padding: 18,
    marginBottom: 14,
  },
  questionIndex: {
    color: '#4f6ef7',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  questionBody: {
    color: '#d8ddf5',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
    marginBottom: 14,
  },

  optionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#303762',
    backgroundColor: '#13172e',
    marginBottom: 8,
    gap: 10,
  },
  optionChipSelected: {
    borderColor: '#4f6ef7',
    backgroundColor: '#1d2855',
  },
  optionDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#303762',
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionDotSelected: { borderColor: '#4f6ef7' },
  optionDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4f6ef7',
  },
  optionBody: {
    color: '#c0c8e8',
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
  },
  optionBodySelected: {
    color: '#d8ddf5',
    fontWeight: '600',
  },

  resultCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 32,
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
  },
  resultCardPass: {
    backgroundColor: '#1b3d2e',
    borderColor: '#2ecc71',
  },
  resultCardFail: {
    backgroundColor: '#2e1b1b',
    borderColor: '#e05c7a',
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: '800',
  },
  resultTitlePass: { color: '#2ecc71' },
  resultTitleFail: { color: '#e05c7a' },
  resultSubtitle: {
    color: '#9099b2',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
  },
  retakeBtn: {
    backgroundColor: '#4f6ef7',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
    marginTop: 8,
  },
  retakeBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },

  questionDotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#1a1f3c',
    borderBottomWidth: 1,
    borderBottomColor: '#242a4e',
    flexWrap: 'wrap',
    gap: 6,
  },
  questionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#303762',
  },
  questionDotActive: {
    width: 20,
    borderRadius: 4,
    backgroundColor: '#4f6ef7',
  },
  questionDotAnswered: { backgroundColor: '#2ecc71' },

  questionNavBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1f3c',
    borderTopWidth: 1,
    borderTopColor: '#242a4e',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 28,
    gap: 12,
  },
  questionNavBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    borderRadius: 12,
    backgroundColor: '#242a4e',
    gap: 6,
  },
  questionNavBtnDisabled: { opacity: 0.35 },
  questionNavBtnText: {
    color: '#d8ddf5',
    fontSize: 14,
    fontWeight: '600',
  },
  questionNavNextBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    borderRadius: 12,
    backgroundColor: '#4f6ef7',
    gap: 6,
    shadowColor: '#4f6ef7',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
  },
  questionNavNextBtnMuted: {
    backgroundColor: '#2a3070',
    shadowOpacity: 0,
    elevation: 0,
  },
  questionNavNextBtnDisabled: {
    backgroundColor: '#303762',
    shadowOpacity: 0,
    elevation: 0,
  },
  questionNavNextBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
});
