import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  kvWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  sheet: {
    backgroundColor: '#1a1f3c',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#303762',
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: '#303762',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 24,
  },
  centeredBody: {
    alignItems: 'center',
    paddingVertical: 24,
    gap: 12,
  },
  bodyText: {
    color: '#d8ddf5',
    fontSize: 14,
    textAlign: 'center',
  },
  bodySubText: {
    color: '#9099b2',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
  },
  iconRow: {
    alignItems: 'center',
    marginBottom: 12,
  },
  title: {
    color: '#d8ddf5',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    color: '#9099b2',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  coursePill: {
    backgroundColor: '#13172e',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#303762',
    padding: 12,
    marginBottom: 12,
    alignItems: 'center',
    gap: 4,
  },
  coursePillLabel: {
    color: '#9099b2',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  coursePillValue: {
    color: '#d8ddf5',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 20,
  },
  namePill: {
    backgroundColor: '#13172e',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#303762',
    padding: 14,
    marginBottom: 20,
    alignItems: 'center',
    gap: 4,
  },
  namePillLabel: {
    color: '#4f6ef7',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  namePillValue: {
    color: '#d8ddf5',
    fontSize: 17,
    fontWeight: '700',
  },
  inputLabel: {
    color: '#9099b2',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: '#13172e',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#303762',
    color: '#d8ddf5',
    fontSize: 15,
    paddingHorizontal: 16,
    paddingVertical: 13,
    marginBottom: 8,
  },
  inputValid: {
    borderColor: '#2ecc71',
  },
  mismatchHint: {
    color: '#e05c7a',
    fontSize: 12,
    marginBottom: 12,
  },
  matchHint: {
    color: '#2ecc71',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 12,
  },
  confirmBtn: {
    backgroundColor: '#4f6ef7',
    borderRadius: 14,
    paddingVertical: 15,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    shadowColor: '#4f6ef7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  confirmBtnDisabled: {
    backgroundColor: '#303762',
    shadowOpacity: 0,
    elevation: 0,
  },
  confirmBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  cancelBtn: {
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  cancelBtnText: {
    color: '#9099b2',
    fontSize: 14,
  },
  closeBtn: {
    backgroundColor: '#242a4e',
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 32,
    marginTop: 8,
  },
  closeBtnText: {
    color: '#d8ddf5',
    fontSize: 14,
    fontWeight: '600',
  },
});
